2.2.1 Notation 

For two vectors. x and. y in.n-dimensional real vector space.Rn, we define the inner 
product by.⟨x, y⟩ Δ xTy, and the Euclidean norm or.l2 norm by

$$ \|\mathcal X \| \overset{\Delta}{=} \sqrt{ \langle x,x \rangle } = \sqrt{ \sum_{i=1}^{n} |x_i|^2}$$


**2.2.2 Matrix Rank**

In [2]:
import numpy as np 
import numpy.linalg as LA 

x = np.array([5,6]) 
A = np.array([[1,2],[3,4]])

[17 39]


the multiplication of matrix. A and vector. x is coded as A@x

In [ ]:
b=A@x 
print(b) 

The norm of b is computed using the norm function in LA (numpy.linalg) as 

In [3]:
print(LA.norm(b, ord=2)) 

42.5440947723653


The rank of A is also easily computed using the matrix_rank function in LA as 

In [4]:
print(LA.matrix_rank(A)) 

2


Finally, let us compute the matrices in (2.18): 

The first line defines the following.3 × 2 matrix:

$$\mathbf{A} = \begin{bmatrix}1 & 2\\3 & 4\\5 & 6\end{bmatrix}$$

In [5]:
A = np.array([[1,2],[3,4],[5,6]]) 

The first line computes .B = AT A, where A.T is the transpose of A. 

The second line computes the inverse of . B = AT Ausing inv function in linalg submodule of NumPy

The third line gives .P = A(AT A)−1AT

$$\mathbf{P = A(A^T A)^- A^T} = \begin{bmatrix}0.83 & 0.33 & -0.17\\0.33 & 0.33 & 0.33\\-0.17 & 0.33 & 0.83\end{bmatrix}$$


In [6]:
B = A.T @ A 
C = LA.inv(B) 
P = A @ C @ A.T 
print(P)

[[ 0.83333333  0.33333333 -0.16666667]
 [ 0.33333333  0.33333333  0.33333333]
 [-0.16666667  0.33333333  0.83333333]]


the line gives .Q = I − P, where eye(3) is the identity matrix in.R3

$$\mathbf{Q = I - P} = \begin{bmatrix}0.17 & -0.33 & 0.17\\-0.33 & 0.67 & -0.33\\0.17 & -0.33 & 0.17\end{bmatrix}$$


In [7]:
Q = np.eye(3) - P 
print(Q) 

[[ 0.16666667 -0.33333333  0.16666667]
 [-0.33333333  0.66666667 -0.33333333]
 [ 0.16666667 -0.33333333  0.16666667]]


**2.2.3 Positive and Non-negative Matrices**

If the elements in. A are all positive (or non-negative), then. A is said to be positive (or non-negative)

If the row sums of . A are all. 1, that is, if

$$ a_{i1} + a_{i2} +···+ a_{in} = 1 $$
    
holds for all.i ∈ {1, 2,..., n}, then. A is said to be a stochastic matrix

The following matrix is a stochastic matrix:

$$\mathbf{A_1} = \frac{1}{4} \begin{bmatrix}2 & 0 & 2 \\ 1 & 2 & 1\\ 0 & 2 & 2\end{bmatrix}$$


In [8]:
A1 = np.array([[2,0,2],[1,2,1],[0,2,2]])/4 
v = np.ones(3) 
print(A1 @ v)

[1. 1. 1.]


A stochastic matrix .A is said to be a doubly stochastic matrix if .AT is also stochastic.

the following matrix is a doubly stochastic matrix:

$$\mathbf{A_2} = \frac{1}{4} \begin{bmatrix}2 & 0 & 2 \\ 1 & 2 & 1\\ 1 & 2 & 1\end{bmatrix}$$

In [9]:
A2 = np.array([[2,0,2],[1,2,1],[1,2,1]])/4 
v = np.ones(3) 
print(A2 @ v) 
print(A2.T @ v) 

[1. 1. 1.]
[1. 1. 1.]
