
### 2.2.6 Spectral Mapping Theorem

The Spectral Mapping Theorem is a fundamental result in linear algebra and functional analysis. It relates the spectrum (set of eigenvalues) of a matrix or linear operator to the spectrum of a function applied to that matrix or operator.

#### Statement of the Theorem

If \( A \) is a square matrix and \( f \) is a complex-valued function that is analytic on the spectrum of \( A \), then the spectrum of \( f(A) \) is given by:
$$ \sigma(f(A)) = \{ f(\lambda) : \lambda \in \sigma(A) \} $$
where \($ \sigma(A)$ \) denotes the spectrum of \( A \).

#### Intuition

The theorem essentially tells us that if you know the eigenvalues of a matrix \( A \), you can determine the eigenvalues of \( f(A) \) by simply applying the function \( f \) to each eigenvalue of \( A \).

#### Example

Let's consider a simple example to illustrate this:

1. **Matrix \( A \)**:
   $
   A = \begin{pmatrix}
   2 & 1 \\
   0 & 3
   \end{pmatrix}
   $
   The eigenvalues of $ ( A ) are ( \lambda_1 = 2 ) and ( \lambda_2 = 3 )$.

2. **Function \( f(x) = x^2 \)**:
   We want to find the eigenvalues of \( $ f(A) = A^2 $\).

3. **Applying the Theorem**:
   According to the Spectral Mapping Theorem, the eigenvalues of \($ A^2 $\) are \( $f(\lambda_1) = 2^2 = 4 $\) and \($ f(\lambda_2) = 3^2 = 9 $ \).

4. **Verification**:
   Let's compute \( $ A^2 $ \) to verify:
   $
   A^2 = \begin{pmatrix}
   2 & 1 \\
   0 & 3
   \end{pmatrix} \begin{pmatrix}
   2 & 1 \\
   0 & 3
   \end{pmatrix} = \begin{pmatrix}
   4 & 5 \\
   0 & 9
   \end{pmatrix}
   $
   The eigenvalues of \( $ A^2 $ \) are indeed 4 and 9, confirming the theorem.

### Application in Multi-Agent Systems

In the context of multi-agent systems, the Spectral Mapping Theorem is useful for analyzing the stability and dynamics of the system. For example, if you have a network of agents represented by a graph, the eigenvalues of the adjacency matrix or Laplacian matrix can provide insights into the system's behavior. Applying functions to these matrices (like exponentiation for continuous-time systems) and using the Spectral Mapping Theorem helps in understanding how the system evolves over time.

Example 2.5 To check Theorem 2.6, let us consider the following matrix: 

   $$
   A = \begin{pmatrix}
   0 & -1 & -1 \\
   -1 & 1 & 0 \\
   -1 & 0 & 1 \\
   \end{pmatrix}
   $$

   The eigenvalues are obtained by 



In [ ]:
import numpy as np 
import numpy.linalg as LA 
A = np.array([[0,-1,-1],[-1,1,0],[-1,0,1]]) 
s, V = LA.eig(A) 
print(s) 


[-1.  2.  1.]


From the result, the eigenvalues are .−1, . 2, and . 1. Then, let us consider another 
matrix 
$$ B = A^2 + A + I $$
The eigenvalues of. B are obtained from Theorem 2.6 as 
$$ (−1)^2 + (−1) + 1 = 1 \space ,\space 2^2 + 2 + 1 = 7 \space ,\space 1^2 + 1 + 1 = 3 $$
To confirm this, we run the following code:

In [3]:
B=A@A+A+ np.eye(3) 
print(B)
s2, V2 = LA.eig(B) 
print(s2)

[[ 3. -2. -2.]
 [-2.  4.  1.]
 [-2.  1.  4.]]
[1. 7. 3.]
