### **2.2.4 Eigenvalues**


### What are Eigenvalues?

Eigenvalues are special numbers associated with a matrix. In the context of multi-agent systems, they help us understand the behavior of the system, especially in terms of stability and dynamics.

### Why are Eigenvalues Important?

1. **Stability**: Eigenvalues can tell us if the system is stable. If all eigenvalues have negative real parts, the system is stable.
2. **Dynamics**: They help describe how the system evolves over time. For example, they can indicate how fast agents in a multi-agent system reach consensus.

### Simple Example

Imagine a group of robots trying to align their directions. We can represent their interactions with a matrix \( A \). The eigenvalues of \( A \) will tell us how the directions of the robots change over time.

### Step-by-Step Example

1. **Matrix Representation**: Suppose we have a matrix \( A \):
   $$
   A = \begin{pmatrix}
   2 & 1 \\
   1 & 2
   \end{pmatrix}
   $$

2. **Characteristic Equation**: To find the eigenvalues, we solve the characteristic equation:
   $$
   \text{det}(A - \lambda I) = 0
   $$
   For our matrix \( A \):
   $$
   \text{det}\begin{pmatrix}
   2 - \lambda & 1 \\
   1 & 2 - \lambda
   \end{pmatrix} = 0
   $$

3. **Solve for Eigenvalues**: This simplifies to:
   $$
   (2 - \lambda)^2 - 1 = 0 \\
   \lambda^2 - 4\lambda + 3 = 0 \\
   (\lambda - 3)(\lambda - 1) = 0
   $$
   So, the eigenvalues are $( \lambda_1 = 3 ) and ( \lambda_2 = 1 )$ .

### Interpretation

- **Eigenvalue \( $ \lambda_1 = 3 $ \)**: Indicates a faster change in the system.
- **Eigenvalue \( $ \lambda_2 = 1 $ \)**: Indicates a slower change.

In a multi-agent system, these eigenvalues help us understand how quickly the agents will align their directions.


In [1]:
import numpy as np 
import numpy.linalg as LA 
A = np.array([[1,0,0],[0,1,1],[0,0,1]]) 
s, V = LA.eig(A) 
print(s) 
print(V) 

[1. 1. 1.]
[[ 1.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  1.00000000e+00 -1.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  2.22044605e-16]]


The first row vector, which is s, implies that. A has the eigenvalue 1 with algebraic 
multiplicity 3. Then, the first and second column vectors in V are linearly independent, 
but the third column vector is dependent, ignoring.2.22 × 10−16, on the second one. It 
follows that there are two linearly independent eigenvectors, and hence the geometric 
multiplicity is 2